### ISSUE TITLE
Create an express app

### ISSUE THREAD

**Issue by Steven-Gassert** [saidah-neves/LiveEngage-Technical-Domains#1]
### Description
 in order to have a server which will take requests from slack, we'll need an express server listening, ready to map a request to the teams that correspond with that query

### Acceptance criteria

- [ ] When you make a request to this server at the `GET /domains` endpoint, it will return a list of domains available

**Comment by Steven-Gassert** [comment]
res.send(['domain1', 'domain2'])

**Comment by Steven-Gassert** [comment]
@saidah-neves in order to complete this issue, lets make our server in `app.js` respond to requests at the `/domains` endpoint rather than the base route

**Comment by saidah-neves** [comment]
Hi @Steven-Gassert can you please clarify a little bit more on the steps above? Not clear on the` requests at the /domains endpoint `

**Comment by Steven-Gassert** [comment]
@saidah-neves right now your express app responds to requests at the base route `https://yourserver:4000`, instead, we would like your server to respond to requests at `https://yourserver:4000/domains`. It would be worth reading up on https://expressjs.com/en/guide/routing.html

**Comment by saidah-neves** [comment]
Closing as complete
