### ISSUE TITLE
Map a keyword to a domain

### ISSUE THREAD

**Issue by Steven-Gassert** [saidah-neves/LiveEngage-Technical-Domains#2]
### Description
We want to parse out the keyword that our slack app will send us. Once we have that keyword, we'll check to see if it exists in any of our domain mappings

### Acceptance Criteria

- [ ] When a request is sent containing query param with a key word inside, we either 1) return the team associated with that key word. Or 2) send a message saying something like "sorry we don't have a team for that key word", and maybe display the mappings that we have.

**Comment by Steven-Gassert** [comment]
```
const domainMappings = {
  team1: ['Assistant', 'IAM'],
  team2: ['Cirrus', 'bluemix']
}
```

Inside your route:
```
function(req, res) {
  const keyWord = req.query.keyword
  // for every domain mapping, check to see if the value of that mapping exists in the keyword sent. If so return the team name
}
```

```
res.send(teamName);
```

**Comment by Steven-Gassert** [comment]
good to understand how express apps parse parameters on a request https://expressjs.com/en/guide/routing.html

**Comment by saidah-neves** [comment]
Map a keyword to a domai completed
